// GENERATED by scripts/build-icons.mjs from design/system/icons/*.svg. DO NOT EDIT.
import type { LaunchTypeId } from "@/config/armory";

export type IconEl = [tag: "circle" | "rect" | "path" | "line" | "polyline" | "polygon" | "ellipse", attrs: Record<string, string>];
export const TYPE_ICON_ELEMENTS: Record<LaunchTypeId, readonly IconEl[]> = {
  plain: [["circle",{"cx":"12","cy":"12","r":"8.5"}],["circle",{"cx":"12","cy":"12","r":"4.5"}]],
  hybrid: [["circle",{"cx":"7.5","cy":"7.5","r":"4"}],["rect",{"x":"13","y":"12","width":"7.5","height":"9","rx":"1.6"}],["path",{"d":"M13.5 5.5h3.5a2 2 0 0 1 2 2V10"}],["path",{"d":"m17 8.5 2 2 2-2"}],["path",{"d":"M10.5 18.5H7a2 2 0 0 1-2-2V14"}],["path",{"d":"m7 15.5-2-2-2 2"}]],
  burn: [["path",{"d":"M12 21c-3.9 0-6.5-2.6-6.5-6.2 0-3.3 2.3-5.4 3.6-7.9.4 1.6 1.3 2.7 2.4 3.2.1-3.1 1.3-5.5 3.5-7.1-.3 2.9.7 4.9 2 6.6 1 1.4 1.5 2.8 1.5 4.7 0 3.9-2.6 6.7-6.5 6.7Z"}],["path",{"d":"M12 21c-1.6 0-2.7-1.1-2.7-2.6 0-1.4.9-2.3 1.6-3.5.6.8 1.3 1 2 .6.4 1 1.8 1.7 1.8 3.1 0 1.4-1.1 2.4-2.7 2.4Z"}]],
  tax: [["circle",{"cx":"12","cy":"12","r":"8.5"}],["path",{"d":"M12 3.5V12l6 6"}],["path",{"d":"M12 12l-6.4 5.6"}]],
  raffle: [["path",{"d":"M3.5 9V7a1 1 0 0 1 1-1h15a1 1 0 0 1 1 1v2a3 3 0 0 0 0 6v2a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1v-2a3 3 0 0 0 0-6Z"}],["path",{"d":"M14.5 6.5v1.5M14.5 11.25v1.5M14.5 16v1.5"}]],
};
