[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hybrid_launch = "9Loc4hQZJh4SuBCGPiPs1wAfwywUAM7av5upyGHfc6Q8"
hybrid_vault = "BEfL9dccCUtgBVfLmJieeSr3ju29fpVqLM3NgttxqXqG"

[provider]
cluster = "localnet"
wallet = "/workspace/launchpad/.keys/devnet-only-deployer.json"

[scripts]
test = "cargo test --workspace --locked -- --show-output"

[hooks]

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
