#!/usr/bin/env node
/** Generates src/components/armory/typeIcons.ts from design/system/icons/*.svg (inlined, so
 * currentColor works and the CSP needs nothing new). Run: npm run icons. Do not hand-edit. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.resolve(here, "../../design/system/icons");
const map = { plain: "plain", hybrid: "hybrid", burn: "burn", tax: "tax-split", raffle: "raffle" };
const body = Object.entries(map).map(([id, file]) => {
  const svg = fs.readFileSync(path.join(dir, `${file}.svg`), "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/<title>[\s\S]*?<\/title>/, "").trim();
  // Parse into [tag, attrs] pairs (no innerHTML at runtime). Only plain shape elements are allowed.
  const els = [];
  const rest = inner.replace(/<(circle|rect|path|line|polyline|polygon|ellipse)\s+([^>]*?)\/>/g, (_, tag, attrs) => {
    const a = {};
    for (const [, k, v] of attrs.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
      if (!/^(d|cx|cy|r|rx|ry|x|y|x1|y1|x2|y2|width|height|points)$/.test(k)) throw new Error(`attr ${k} not allowed in ${file}.svg`);
      a[k] = v;
    }
    els.push([tag, a]);
    return "";
  });
  if (rest.trim()) throw new Error(`unsupported markup in ${file}.svg: ${rest.trim().slice(0, 60)}`);
  return `  ${id}: ${JSON.stringify(els)},`;
});
fs.writeFileSync(
  path.resolve(here, "../src/components/armory/typeIcons.ts"),
  `// GENERATED by scripts/build-icons.mjs from design/system/icons/*.svg. DO NOT EDIT.\nimport type { LaunchTypeId } from "@/config/armory";\n\nexport type IconEl = [tag: "circle" | "rect" | "path" | "line" | "polyline" | "polygon" | "ellipse", attrs: Record<string, string>];\nexport const TYPE_ICON_ELEMENTS: Record<LaunchTypeId, readonly IconEl[]> = {\n${body.join("\n")}\n};\n`,
);
console.log("typeIcons.ts written");
