#!/usr/bin/env node
/**
 * Generates src/styles/tokens.css from the Creative Director's W3C design tokens
 * (design/system/tokens.json). Run: `npm run tokens`. Do not hand-edit the output.
 *
 * Every leaf token becomes a CSS custom property: color.accent.default -> --arm-color-accent-default.
 * Composite values (typography objects, mascot sizes, font settings) are flattened one level.
 * References like "{font.family.headline}" become var(--arm-font-family-headline).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "../../design/system/tokens.json");
const out = path.resolve(here, "../src/styles/tokens.css");
const tokens = JSON.parse(fs.readFileSync(src, "utf8"));

const kebab = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase();
const ref = (v) =>
  typeof v === "string" ? v.replace(/\{([^}]+)\}/g, (_, p) => `var(--arm-${p.split(".").map(kebab).join("-")})`) : v;
const fmt = (v) => {
  if (Array.isArray(v)) return v.map((f) => (/[\s]/.test(f) && !/^ui-|^system-ui$|^-apple/.test(f) ? `"${f}"` : f)).join(", ");
  if (typeof v === "number") return String(v);
  return ref(String(v));
};

const lines = [];
const walk = (node, p) => {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    const name = [...p, kebab(k)];
    if (v && typeof v === "object" && "$value" in v) {
      const val = v.$value;
      if (val && typeof val === "object" && !Array.isArray(val)) {
        for (const [sk, sv] of Object.entries(val)) lines.push(`  --arm-${[...name, kebab(sk)].join("-")}: ${fmt(sv)};`);
      } else {
        lines.push(`  --arm-${name.join("-")}: ${fmt(val, v.$type)};`);
      }
    } else if (v && typeof v === "object") {
      walk(v, name);
    }
  }
};
walk(tokens, []);

const css = `/*
 * GENERATED by scripts/build-tokens.mjs from design/system/tokens.json. DO NOT EDIT.
 * Regenerate with: npm run tokens
 * Tailwind utilities are mapped to these variables in src/app/globals.css (@theme).
 */
:root {
${lines.join("\n")}
}
`;
fs.writeFileSync(out, css);
console.log(`tokens.css: ${lines.length} variables written to ${path.relative(process.cwd(), out)}`);

// Breakpoints: media queries can't use var(), so emit literal Tailwind v4 --breakpoint-* values.
const bp = tokens.breakpoint ?? {};
const bpLines = ["sm", "md", "lg", "xl"].map((k) => {
  const v = bp[k]?.$value;
  if (typeof v !== "string" || !/^\d+px$/.test(v)) throw new Error(`tokens.json breakpoint.${k} missing or not px: ${v}`);
  return `  --breakpoint-${k}: ${v};`;
});
const bpOut = path.resolve(here, "../src/styles/breakpoints.css");
fs.writeFileSync(
  bpOut,
  `/*
 * GENERATED by scripts/build-tokens.mjs from design/system/tokens.json (breakpoint.*). DO NOT EDIT.
 * Mobile-first min-width breakpoints; every sm:/md:/lg:/xl: utility follows these.
 */
@theme {
${bpLines.join("\n")}
}
`,
);
console.log(`breakpoints.css: ${bpLines.map((l) => l.trim()).join(" ")}`);
